"""Init

Revision ID: 7e88b749a3ac
Revises: 96c64cb4b45c
Create Date: 2024-03-26 15:02:45.147714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e88b749a3ac'
down_revision: Union[str, None] = '96c64cb4b45c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contacts', 'birthday',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.Date(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contacts', 'birthday',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=15),
               nullable=True)
    # ### end Alembic commands ###
