"""Init

Revision ID: 96e55ed53257
Revises: 7cf9aec12aaf
Create Date: 2024-03-26 00:30:09.542344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96e55ed53257'
down_revision: Union[str, None] = '7cf9aec12aaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contacts', 'birthday',
               existing_type=sa.DATE(),
               type_=sa.String(length=15),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contacts', 'birthday',
               existing_type=sa.String(length=15),
               type_=sa.DATE(),
               existing_nullable=True)
    # ### end Alembic commands ###
